server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projetoDb
    username: postgres
    password: estoquefacilsi20172
  jpa:
    hibernate:
      ddl-auto: create-drop